### ISSUE TITLE
Incorrect logging in success message

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/cloud-tools-for-eclipse#694] opened 2016-09-14 14:51 UTC
When you deny authorization while logging in to Google you get this window. The message implies logging in was successful even though the user deny access.

![screenshot from 2016-09-14 10 55 54](https://cloud.githubusercontent.com/assets/6805942/18517308/d66902ec-7a69-11e6-9b46-a38a54113efc.png)

**Comment by chanseokoh** [comment] 2016-09-14 15:09
I am closing this as a duplicate of #649.

**Closed by chanseokoh** 2016-09-14 15:09 UTC
Labels: bug
