### ISSUE TITLE
Fishfood: Project name not propagated from project creation to deployment 

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/cloud-tools-for-eclipse#669] opened 2016-09-06 17:56 UTC
Eclipse: Neon Release (4.6.0)
Google Cloud Platform for Eclipse 4.5 and 4.6	0.1.0.201608301906

When creating a new project, asks for a GCP project ID, but does not pre-fill the value in deployment.

**Comment by akerekes** [comment] 2016-09-06 18:14
Duplicate of #646 
The next version will have this.

**Closed by akerekes** 2016-09-06 18:14 UTC
